### PR TITLE
Spanish translations

### PR DESCRIPTION
**Pull request by dreinon**

### CODE REVIEW

**Comment by djhi** [comment]
Hi and thank you for taking the time to open this PR. We won't merge because we cannot maintain this language. I invite you to publish it yourself and to update your PR to include a link to your own repository.

**Comment by dreinon** [comment]
@djhi Done!

**Review by djhi — APPROVED** [review]
Thanks!

**Comment by dreinon** [comment]
Hi! Is there any timeline on merging this PR? Thanks!

**Comment by djhi** [comment]
@dreinon I'm sorry I didn't get time to revisit this package. We released version `2.0.0` though. If you can check whether your package must be updated, I'll be happy to add a mention ih the README

**Comment by djhi** [comment]
Thanks again and sorry for the delay. It's merged and published in `2.0.4`

**Pull request merged**
