### PR TITLE
Upgrade to react-admin v5

### LINKED ISSUE #60: Upgrade to RA 5?
Hi Team,
Is there a plan to upgrade this package to use with `react-admin` 5?
Mainly in my case, the migration from `react-query` to `@tanstack/react-query` is breaking my app.
**query client error.**
Thanks.

### PR DESCRIPTION
**Pull request by mrkpatchaa**
Marked as a WIP because I can't test locally, and installing npm from my github is not working.
Fixes #60

### CODE REVIEW

**Comment by slax57** [comment]
Thanks for initializing this PR!

I'll try to take over to see if I can finish the migration.

I'll also need to do some more checks to ensure [ra-data-postgrest](https://github.com/raphiniert-com/ra-data-postgrest) is fully compatible with RA v5 (in which case I'll open a PR to fix the peer dependencies declaration).

**Comment by mrkpatchaa** [comment]
Great. Looking forward to hearing from you.

**Comment by slax57** [comment]
PR to update `ra-data-postgrest`'s peerDeps: https://github.com/raphiniert-com/ra-data-postgrest/pull/142

**Comment by slax57** [comment]
PR is all green! :white_check_mark: 
Just waiting to see with the team if this needs to be merged on the `main` branch or the `next` branch. Stay tuned.

**Review by djhi — APPROVED** [review]

**Comment by slax57** [comment]
We can merge on `master`. However the 3.0.0 release will have to wait for either https://github.com/raphiniert-com/ra-data-postgrest/pull/142  to get merged, or for us to fork and release `ra-data-postgrest`.

**Pull request merged**
